# Generated by Django 5.2.13 on 2026-04-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_saleschannel_company_tag_company_taxrate_company_and_more'),
        ('products', '0003_add_reorder_rule'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('Standard', 'Factura'), ('CreditNote', 'Nota de crédito')], default='Standard', max_length=12)),
                ('status', models.CharField(choices=[('Draft', 'Borrador'), ('Approved', 'Aprobada'), ('PartiallyPaid', 'Parcialmente pagada'), ('Paid', 'Pagada'), ('Voided', 'Anulada'), ('Rectified', 'Rectificada')], default='Draft', max_length=15)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('provider_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('provider_vat_snapshot', models.CharField(blank=True, max_length=20)),
                ('provider_address_snapshot', models.JSONField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(default='Transfer 30 days', max_length=50)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_retention', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='providers.provider')),
                ('rectified_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('discount_type', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseinvoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLineTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=50)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_retention', models.BooleanField(default=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='purchases.purchaseinvoiceline')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('approved', 'Aprobado'), ('sent', 'Enviado'), ('payment', 'Pago'), ('paid', 'Pagado'), ('voided', 'Anulado'), ('rectified', 'Rectificado')], max_length=20)),
                ('action', models.CharField(max_length=300)),
                ('actor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('Transfer', 'Transferencia'), ('DirectDebit', 'Domiciliación'), ('Card', 'Tarjeta'), ('Cash', 'Efectivo'), ('Other', 'Otro')], default='Transfer', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.purchaseinvoice')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('concept', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('valid_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviado', 'Enviado'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado'), ('Expirado', 'Expirado')], default='Borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotes', to='providers.provider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=10)),
                ('pattern', models.CharField(default='{PREFIX}-{YEAR}-{SEQ:4}', max_length=50)),
                ('next_seq', models.IntegerField(default=1)),
                ('reset_yearly', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_series', to='accounts.company')),
            ],
            options={
                'verbose_name_plural': 'purchase series',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='purchases.purchaseseries'),
        ),
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('series', 'number'), name='unique_purchase_invoice_number_per_series'),
        ),
    ]
