# Generated by Django 5.2.13 on 2026-04-24 12:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_saleschannel_company_tag_company_taxrate_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_type', models.CharField(choices=[('Company', 'Empresa'), ('Person', 'Persona')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=10)),
                ('vat_id', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='España', max_length=100)),
                ('payment_method', models.CharField(blank=True, default='Transferencia 30 días', max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=34)),
                ('avatar_color', models.CharField(blank=True, max_length=200)),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='accounts.company')),
                ('linked_contacts', models.ManyToManyField(blank=True, to='providers.provider')),
                ('tags', models.ManyToManyField(blank=True, related_name='providers', to='core.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Reunión', 'Reunión'), ('Llamada', 'Llamada'), ('Email', 'Email'), ('Visita', 'Visita'), ('Otro', 'Otro')], max_length=20)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='providers.provider')),
            ],
            options={
                'verbose_name_plural': 'provider activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('concept', models.CharField(max_length=300)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Borrador'), ('Approved', 'Aprobado'), ('PartiallyPaid', 'Parcialmente pagado'), ('Paid', 'Pagado'), ('Cancelled', 'Cancelado')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='providers.provider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
